### ISSUE TITLE
Vector table for M4

### ISSUE THREAD

**Issue by 0xkelvin** [Ion-Mobility/tock#1]
Hello @xobs 

I am getting confuse, should i change "CortexM7" to "CortexM4" in definition below : 

https://github.com/Ion-Mobility/tock/blob/f/add_new_chip_s32k144/chips/s32k144/src/lib.rs#L61

**Comment by xobs** [comment]
Yes, you should use `CortexM4`. It's just giving it a common function name to call when you don't implement an IRQ in order to fill out the interrupt vector table.
