### ISSUE TITLE
S2k14x memory layout

### ISSUE THREAD

**Issue by 0xkelvin** [Ion-Mobility/tock#2]
Hello @xobs @nguyenlkdn 

could you please review this configuration 
https://github.com/Ion-Mobility/tock/blob/f/add_new_chip_s32k144/boards/s32k144_evb/layout.ld

**Comment by xobs** [comment]
Some things to note:

* RAM ends at `0x0007_FFFF` on the S32K144. You can make the program area bigger.
* The S32K144 has 60 kB of RAM, going from `0x1fff_8000` up to `0x2000_6fff`. It's very far away from 1024 kB.
* You will need to create a special "FCF" area at offset `0x400`. You have two options to fix this:

1. Modify https://github.com/Ion-Mobility/tock/blob/f/add_new_chip_s32k144/boards/kernel_layout.ld and insert a `.fcf` region in the correct place. You can see this being done in https://github.com/Ion-Mobility-Systems/gridania-bringup-dvt1/blob/main/148/ld/s32k148.ld#L26 and https://github.com/Ion-Mobility-Systems/gridania-bringup-dvt1/blob/main/148/ld/s32k148.ld#L94-L98
2. Strip out some amount of data from ROM and write a small bootloader at the start. That is, offset 0 will be your stack pointer and offset 4 would be your entrypoint. Then write a bootloader starting at offset 8 that just does the following:

* Load `0x1000` into VTOR
* Load the offset at 0x1000 into the stack pointer
* Load 0x1004 into the program counter

That way the first chunk of memory is unused.

The problem with (2) is that I'm not sure what the alignment requirements are of VTOR. If you can set it to `0x500`, then that's much better than if it needs to be set to `0x1000`.
